version: '3'
services:

  postgres:
    hostname: mypostgres
    image: postgres:14
    container_name: postgres
    restart: on-failure
    ports:
      - 54321:5432
    networks:
      - dataworld
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    hostname: myminio
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - dataworld
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      
  nifi:
    hostname: mynifi
    image: apache/nifi
    container_name: nifi
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin123admin123admin123
    ports:
      - "8080:8080/tcp" # HTTP interface
      - "8443:8443/tcp" # HTTPS interface
    networks:
      - dataworld
    volumes:
      - nifi_data:/opt/nifi/nifi-current
    restart: on-failure

volumes:
  nifi_data:
  postgres_data:
  minio_data:

networks:
    dataworld:
        driver: bridge